name: ci

on:
  push:
    branches:
      - 'main'
      - 'dev'
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}       
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - 
        name: Build and push init image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.init
          push: true
          tags: ${{ steps.meta.images }}:init
      - 
        name: Build and push on-demand image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.demand
          push: true
          tags: ${{ steps.meta.images }}:on-demand
